export const mainActions = {
    FETCH_CATEGORY_POSTS: 'FETCH_CATEGORY_POSTS',
    FETCH_CATEGORY_POSTS_SUCCESS: 'FETCH_CATEGORY_POSTS_SUCCESS',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    SELECT_CATEGORY: 'SELECT_CATEGORY'
};

export const postActions = {
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS'
};
