export const mainActions = {
    FETCH_CATEGORY_POSTS: 'FETCH_CATEGORY_POSTS',
    FETCH_POST_SUCCESS: 'FETCH_POST_SUCCESS',
    FETCH_CATEGORY_POSTS_SUCCESS: 'FETCH_CATEGORY_POSTS_SUCCESS',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    RESET_LOADING_TEXT: 'RESET_LOADING_TEXT',
    SELECT_CATEGORY: 'SELECT_CATEGORY',
    SET_LOADING_TEXT: 'SET_LOADING_TEXT',
};

export const postActions = {
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS'
};
